AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'

Rails:
  Enabled:                     true

Style/Documentation:
  Enabled:                     false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Exclude:
    - app/models/ability.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - app/models/ability.rb

Metrics/MethodLength:
  Exclude:
    - app/models/ability.rb

Metrics/PerceivedComplexity:
    Exclude:
      - app/models/ability.rb
