language: ruby
rvm:
  - 2.3
  - ruby-head
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - rake db:create
  #- if [ "${DB}" == "mysql" ]; then mysql -e 'create database eotc_helper_test'; fi
  #- if [ "${DB}" == "postgresql" ]; then psql -c 'create database eotc_helper_test' -U postgres; fi
