language:            ruby

rvm:
  - 2.3
  - ruby-head

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

script:
  - RAILS_ENV=test
  - bundle exec rake --trace db:migrate test
before_script:
  - bundle exec rake db:create test

jobs:
  include:
    - stage:         Lint
      before_script:
        - echo "Enforcing styles..."
      script:
        - rubocop -a --format worst -c .rubocop/yml > .rubocop/out; echo Exited with status $? >> .rubocop/out
        - ruby .rubocop/script_fail_checker.rb
      after_script:
        - cat .rubocop/out
        - ruby .rubocop/after_script.rb
      gemfile:       .rubocop/Gemfile
      env:
