language:            ruby

rvm:
  - 2.3
  - ruby-head

env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

script:
  - RAILS_ENV=test
  - bundle exec rake --trace db:migrate test
before_script:
  - bundle exec rake db:create

jobs:
  include:
    - stage:         Lint
      before_script: echo "Enforcing styles..."
      script:        rubocop --autocorrect --format json | tee temp_rubocop_output.json
      gemfile:       Gemfile-Rubocop
      env:           
