postgresql: &postgresql
  adapter: postgresql
  username: rails_ps
  password: rails_ps
  database: eotc_helper_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *postgresql

development:
  <<: *defaults

test:
  <<: *defaults

production:
  # username: <%=  %>
  # password: <%=  %>
  <<: *defaults
  # TODO: Add erb-echo of credentials
