postgresql: &postgresql
  adapter: postgresql
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASS"] || "" %>
  database: eotc_helper_<%= Rails.env %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: <%= ENV["POSTGRES_HOST"] || 'localhost' %>
  <<: *postgresql

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
